In [17]:
#Importing all the required libraries
import numpy as np
import pandas as pd
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [18]:
#Reading and Storing the dataset in variable named HDFC_df
HDFC_df = pd.read_csv("HDB.csv")

In [19]:
#Printing to have a quick look
HDFC_df

Date       Open       High        Low      Close  Adj Close  \
0     16-10-2017  49.330002  49.645000  48.009998  48.264999  46.964260   
1     17-10-2017  48.130001  48.334999  47.244999  47.299999  46.025269   
2     18-10-2017  48.060001  48.195000  47.435001  47.634998  46.351238   
3     19-10-2017  47.340000  47.830002  46.884998  47.779999  46.492329   
4     20-10-2017  47.910000  48.169998  47.615002  48.000000  46.706398   
...          ...        ...        ...        ...        ...        ...   
1254  10-10-2022  57.700001  58.570000  57.500000  57.599998  57.599998   
1255  11-10-2022  56.990002  57.389999  56.360001  56.470001  56.470001   
1256  12-10-2022  56.840000  57.590000  56.639999  56.869999  56.869999   
1257  13-10-2022  55.380001  57.889999  55.220001  57.650002  57.650002   
1258  14-10-2022  58.549999  59.410000  57.959999  57.970001  57.970001   

       Volume   Returns  
0     1696800       NaN  
1     1793200 -1.999374  
2     1940000  0.708239  
3     1066800  0.304395  
4     1119600  0.460439  
...       ...       ...  
1254  1415300  0.261091  
1255  1874800 -1.961800  
1256  1088500  0.708337  
1257  1076200  1.371554  
1258  1752900  0.555072  

[1259 rows x 8 columns]

In [20]:
#Dropping the NA values to ensure accurate results
HDFC_df = HDFC_df.dropna()

In [21]:
#Again printing
HDFC_df

Date       Open       High        Low      Close  Adj Close  \
1     17-10-2017  48.130001  48.334999  47.244999  47.299999  46.025269   
2     18-10-2017  48.060001  48.195000  47.435001  47.634998  46.351238   
3     19-10-2017  47.340000  47.830002  46.884998  47.779999  46.492329   
4     20-10-2017  47.910000  48.169998  47.615002  48.000000  46.706398   
5     23-10-2017  48.150002  48.250000  47.330002  47.330002  46.054459   
...          ...        ...        ...        ...        ...        ...   
1254  10-10-2022  57.700001  58.570000  57.500000  57.599998  57.599998   
1255  11-10-2022  56.990002  57.389999  56.360001  56.470001  56.470001   
1256  12-10-2022  56.840000  57.590000  56.639999  56.869999  56.869999   
1257  13-10-2022  55.380001  57.889999  55.220001  57.650002  57.650002   
1258  14-10-2022  58.549999  59.410000  57.959999  57.970001  57.970001   

       Volume   Returns  
1     1793200 -1.999374  
2     1940000  0.708239  
3     1066800  0.304395  
4     1119600  0.460439  
5     1252000 -1.395824  
...       ...       ...  
1254  1415300  0.261091  
1255  1874800 -1.961800  
1256  1088500  0.708337  
1257  1076200  1.371554  
1258  1752900  0.555072  

[1258 rows x 8 columns]

In [6]:
#Standardising the data to ensure it lies on base axis (0,0)
from sklearn.preprocessing import StandardScaler
std_obj = StandardScaler()

In [7]:
#Using iloc to select only the required columns from the dataset
#We have dropped the date column
#Storing the standardised values in the same variable again
HDFC_df.iloc[:,1:7] = std_obj.fit_transform(HDFC_df.iloc[:, 1:7])
HDFC_df.head()

C:\Users\Aarohi\AppData\Local\Temp\ipykernel_2796\2427364309.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  HDFC_df.iloc[:,1:7] = std_obj.fit_transform(HDFC_df.iloc[:, 1:7])


Date      Open      High       Low     Close  Adj Close    Volume  \
1  17-10-2017 -0.954397 -0.980907 -0.990199 -1.031537  -1.067199  0.098825   
2  18-10-2017 -0.961008 -0.994077 -0.972130 -0.999872  -1.036392  0.242649   
3  19-10-2017 -1.029010 -1.028413 -1.024435 -0.986166  -1.023059 -0.612849   
4  20-10-2017 -0.975175 -0.996429 -0.955012 -0.965372  -1.002828 -0.561120   
5  23-10-2017 -0.952508 -0.988903 -0.982115 -1.028701  -1.064440 -0.431404   

    Returns  
1 -1.999374  
2  0.708239  
3  0.304395  
4  0.460439  
5 -1.395824

In [8]:
#Assigning variable x to the selected columns
#The colon at the start of the [] reprsents that we are selcting all the rows
x = HDFC_df.iloc[:, 1:7]
x

Open      High       Low     Close  Adj Close    Volume
1    -0.954397 -0.980907 -0.990199 -1.031537  -1.067199  0.098825
2    -0.961008 -0.994077 -0.972130 -0.999872  -1.036392  0.242649
3    -1.029010 -1.028413 -1.024435 -0.986166  -1.023059 -0.612849
4    -0.975175 -0.996429 -0.955012 -0.965372  -1.002828 -0.561120
5    -0.952508 -0.988903 -0.982115 -1.028701  -1.064440 -0.431404
...        ...       ...       ...       ...        ...       ...
1254 -0.050546 -0.018078 -0.014955 -0.057968   0.026683 -0.271414
1255 -0.117602 -0.129083 -0.123368 -0.164776  -0.080108  0.178771
1256 -0.131770 -0.110269 -0.096740 -0.126968  -0.042306 -0.591589
1257 -0.269661 -0.082047 -0.231781 -0.053241   0.031409 -0.603640
1258  0.029734  0.060942  0.028791 -0.022995   0.061651  0.059342

[1258 rows x 6 columns]

In [9]:
#Importing sklearn library
import sklearn

In [10]:
#Choosing PCA from sklearn
from sklearn.decomposition import PCA

In [11]:
#Assigning PCA to pca
#The (0.9) represents that we are only capturing the features giving us 90% variability
#Fitting the data in x to our pca model
pca = PCA(0.9)
pca.fit(x)

PCA(n_components=0.9)

In [12]:
#Printing the eigen vectors transposed 
print(pca.components_.T)

[[-0.44256611  0.06441806]
 [-0.44245555  0.07866168]
 [-0.44326983  0.04514144]
 [-0.4429361   0.059313  ]
 [-0.4425861   0.06709137]
 [ 0.14073142  0.98975028]]


In [13]:
#Printing the eigen vectors
print(pca.components_)

[[-0.44256611 -0.44245555 -0.44326983 -0.4429361  -0.4425861   0.14073142]
 [ 0.06441806  0.07866168  0.04514144  0.059313    0.06709137  0.98975028]]


In [14]:
#Printing the eigen values
print(pca.explained_variance_)

[5.0800745  0.91892325]


In [15]:
#Printing the percent variabilty captured by each eigen value
#This is given by the formula = (eigen value/sum of eigen values)
print(pca.explained_variance_ratio_)

[0.84600605 0.15303213]


In [16]:
#This is the Z-Score or PCA1, PCA2 values
z = pca.transform(x)
print(z)

[[ 2.23845671 -0.21831027]
 [ 2.23178117 -0.07266161]
 [ 2.16788606 -0.92712658]
 ...
 [ 0.14169556 -0.61742404]
 [ 0.18311708 -0.63279127]
 [-0.06163486  0.06951515]]
