In [1]:
#Importing all the required libraries
import numpy as np
import pandas as pd
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [2]:
#Reading and Storing the dataset in variable named IDFC_df
IDFC_df = pd.read_csv(r"C:\Users\Aarohi\Downloads\IDFCFIRSTB.NS.csv")

In [3]:
#Printing to have a quick look
IDFC_df

Date       Open       High        Low      Close  Adj Close  \
0     16-10-2017  59.500000  59.549999  57.799999  57.950001  56.770557   
1     17-10-2017  58.200001  58.349998  57.400002  57.450001  56.280735   
2     18-10-2017  57.150002  57.599998  56.099998  56.299999  55.154137   
3     19-10-2017  56.400002  56.700001  56.000000  56.250000  55.105156   
4     23-10-2017  56.700001  56.700001  55.900002  56.400002  55.252106   
...          ...        ...        ...        ...        ...        ...   
1231  10-10-2022  51.500000  54.400002  51.299999  53.750000  53.750000   
1232  11-10-2022  54.000000  54.500000  52.900002  53.099998  53.099998   
1233  12-10-2022  53.099998  55.450001  52.700001  55.099998  55.099998   
1234  13-10-2022  55.299999  55.400002  53.650002  54.450001  54.450001   
1235  14-10-2022  55.799999  56.000000  54.099998  54.299999  54.299999   

        Volume   Returns  
0      8423731       NaN  
1      5056385 -0.862810  
2     12850940 -2.001747  
3      2039693 -0.088807  
4      5292732  0.266672  
...        ...       ...  
1231  47420772  1.415094  
1232  37879776 -1.209306  
1233  64723442  3.766478  
1234  41923792 -1.179668  
1235  37079387 -0.275486  

[1236 rows x 8 columns]

In [4]:
#Dropping the NA values to ensure accurate results
IDFC_df = IDFC_df.dropna()

In [5]:
#Again printing
IDFC_df

Date       Open       High        Low      Close  Adj Close  \
1     17-10-2017  58.200001  58.349998  57.400002  57.450001  56.280735   
2     18-10-2017  57.150002  57.599998  56.099998  56.299999  55.154137   
3     19-10-2017  56.400002  56.700001  56.000000  56.250000  55.105156   
4     23-10-2017  56.700001  56.700001  55.900002  56.400002  55.252106   
5     24-10-2017  56.500000  57.349998  56.200001  57.049999  55.888874   
...          ...        ...        ...        ...        ...        ...   
1231  10-10-2022  51.500000  54.400002  51.299999  53.750000  53.750000   
1232  11-10-2022  54.000000  54.500000  52.900002  53.099998  53.099998   
1233  12-10-2022  53.099998  55.450001  52.700001  55.099998  55.099998   
1234  13-10-2022  55.299999  55.400002  53.650002  54.450001  54.450001   
1235  14-10-2022  55.799999  56.000000  54.099998  54.299999  54.299999   

        Volume   Returns  
1      5056385 -0.862810  
2     12850940 -2.001747  
3      2039693 -0.088807  
4      5292732  0.266672  
5      7794671  1.152477  
...        ...       ...  
1231  47420772  1.415094  
1232  37879776 -1.209306  
1233  64723442  3.766478  
1234  41923792 -1.179668  
1235  37079387 -0.275486  

[1235 rows x 8 columns]

In [6]:
#Standardising the data to ensure it lies on base axis (0,0)
from sklearn.preprocessing import StandardScaler
std_obj = StandardScaler()

In [7]:
#Using iloc to select only the required columns from the dataset
#We have dropped the date column
#Storing the standardised values in the same variable again
IDFC_df.iloc[:,1:7] = std_obj.fit_transform(IDFC_df.iloc[:, 1:7])
IDFC_df.head()

C:\Users\Aarohi\AppData\Local\Temp\ipykernel_11920\1161880612.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IDFC_df.iloc[:,1:7] = std_obj.fit_transform(IDFC_df.iloc[:, 1:7])


Date      Open      High       Low     Close  Adj Close    Volume  \
1  17-10-2017  1.542386  1.470280  1.562745  1.479065   1.390168 -0.938220   
2  18-10-2017  1.432658  1.392602  1.425520  1.358494   1.270571 -0.597154   
3  19-10-2017  1.354280  1.299388  1.414965  1.353252   1.265371 -1.070222   
4  23-10-2017  1.385631  1.299388  1.404409  1.368979   1.280971 -0.927878   
5  24-10-2017  1.364730  1.366709  1.436076  1.437127   1.348569 -0.818401   

    Returns  
1 -0.862810  
2 -2.001747  
3 -0.088807  
4  0.266672  
5  1.152477

In [8]:
#Assigning variable x to the selected columns
#The colon at the start of the [] reprsents that we are selcting all the rows
x = IDFC_df.iloc[:, 1:7]
x

Open      High       Low     Close  Adj Close    Volume
1     1.542386  1.470280  1.562745  1.479065   1.390168 -0.938220
2     1.432658  1.392602  1.425520  1.358494   1.270571 -0.597154
3     1.354280  1.299388  1.414965  1.353252   1.265371 -1.070222
4     1.385631  1.299388  1.404409  1.368979   1.280971 -0.927878
5     1.364730  1.366709  1.436076  1.437127   1.348569 -0.818401
...        ...       ...       ...       ...        ...       ...
1231  0.842213  1.061175  0.918846  1.091142   1.121510  0.915518
1232  1.103472  1.071532  1.087738  1.022993   1.052506  0.498032
1233  1.009419  1.169924  1.066627  1.232681   1.264823  1.672630
1234  1.239326  1.164746  1.166906  1.164533   1.195821  0.674986
1235  1.291578  1.226888  1.214406  1.148806   1.179897  0.463010

[1235 rows x 6 columns]

In [9]:
#Importing sklearn library
#Choosing PCA from sklearn
import sklearn
from sklearn.decomposition import PCA

In [10]:
#Assigning PCA to pca
#The (0.9) represents that we are only capturing the features giving us 90% variability
#Fitting the data in x to our pca model
pca = PCA(0.9)
pca.fit(x)

PCA(n_components=0.9)

In [11]:
#Printing the eigen vectors transposed 
print(pca.components_.T)

[[-0.44648439  0.00343356]
 [-0.44673815  0.04520506]
 [-0.44706627 -0.01133861]
 [-0.4469619   0.02569606]
 [-0.44663819  0.03559878]
 [ 0.04413451  0.99794218]]


In [12]:
#Printing the eigen vectors
print(pca.components_)

[[-0.44648439 -0.44673815 -0.44706627 -0.4469619  -0.44663819  0.04413451]
 [ 0.00343356  0.04520506 -0.01133861  0.02569606  0.03559878  0.99794218]]


In [13]:
#Printing the eigen values
print(pca.explained_variance_)

[4.99730345 0.99515885]


In [14]:
#Printing the percent variabilty captured by each eigen value
#This is given by the formula = (eigen value/sum of eigen values)
print(pca.explained_variance_ratio_)

[0.83220951 0.16572551]


In [15]:
#This is the Z-Score or PCA1, PCA2 values
z = pca.transform(x)
print(z)

[[-3.36752802 -0.79475445]
 [-3.10012528 -0.46407809]
 [-3.03498303 -0.94085513]
 ...
 [-2.49225142  1.79014784]
 [-2.62017131  0.78976762]
 [-2.68771195  0.57970626]]
